/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 08/02/2023 13:41:54
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     168000000
#define MX_SYSCLKFreq_VALUE                     168000000
#define MX_HCLKFreq_Value                       168000000
#define MX_FCLKCortexFreq_Value                 168000000
#define MX_CortexFreq_Value                     168000000
#define MX_AHBFreq_Value                        168000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    84000000
#define MX_APB2TimFreq_Value                    168000000
#define MX_48MHZClocksFreq_Value                84000000
#define MX_EthernetFreq_Value                   168000000
#define MX_I2SClocksFreq_Value                  192000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    168000000

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- TIM5       --------------------------------*/

#define MX_TIM5                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM5_IRQn */
#define MX_TIM5_IRQn_interruptPremptionPriority 0
#define MX_TIM5_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM5_IRQn_Subriority                 0

/*-------------------------------- TIM7       --------------------------------*/

#define MX_TIM7                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM7_IRQn */
#define MX_TIM7_IRQn_interruptPremptionPriority 1
#define MX_TIM7_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM7_IRQn_Subriority                 0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PE6 */
#define MX_PE6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE6_Pin                              PE6
#define MX_PE6_GPIOx                            GPIOE
#define MX_PE6_PinState                         GPIO_PIN_RESET
#define MX_PE6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE6_GPIO_Pin                         GPIO_PIN_6
#define MX_PE6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE5 */
#define MX_PE5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE5_Pin                              PE5
#define MX_PE5_GPIOx                            GPIOE
#define MX_PE5_PinState                         GPIO_PIN_RESET
#define MX_PE5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE5_GPIO_Pin                         GPIO_PIN_5
#define MX_PE5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE8 */
#define MX_PE8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE8_Pin                              PE8
#define MX_PE8_GPIOx                            GPIOE
#define MX_PE8_PinState                         GPIO_PIN_RESET
#define MX_PE8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE8_GPIO_Pin                         GPIO_PIN_8
#define MX_PE8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA0-WKUP */
#define MX_PA0_WKUP_Pin                         PA0_WKUP
#define MX_PA0_WKUP_GPIOx                       GPIOA
#define MX_PA0_WKUP_GPIO_PuPd                   GPIO_NOPULL
#define MX_PA0_WKUP_GPIO_Pin                    GPIO_PIN_0
#define MX_PA0_WKUP_GPIO_Mode                   GPIO_MODE_INPUT

/* Pin PE7 */
#define MX_PE7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE7_Pin                              PE7
#define MX_PE7_GPIOx                            GPIOE
#define MX_PE7_PinState                         GPIO_PIN_RESET
#define MX_PE7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE7_GPIO_Pin                         GPIO_PIN_7
#define MX_PE7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE9 */
#define MX_PE9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE9_Pin                              PE9
#define MX_PE9_GPIOx                            GPIOE
#define MX_PE9_PinState                         GPIO_PIN_RESET
#define MX_PE9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE9_GPIO_Pin                         GPIO_PIN_9
#define MX_PE9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE11 */
#define MX_PE11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE11_Pin                             PE11
#define MX_PE11_GPIOx                           GPIOE
#define MX_PE11_PinState                        GPIO_PIN_RESET
#define MX_PE11_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE11_GPIO_Pin                        GPIO_PIN_11
#define MX_PE11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE10 */
#define MX_PE10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE10_Pin                             PE10
#define MX_PE10_GPIOx                           GPIOE
#define MX_PE10_PinState                        GPIO_PIN_RESET
#define MX_PE10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE10_GPIO_Pin                        GPIO_PIN_10
#define MX_PE10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE13 */
#define MX_PE13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE13_Pin                             PE13
#define MX_PE13_GPIOx                           GPIOE
#define MX_PE13_PinState                        GPIO_PIN_RESET
#define MX_PE13_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE13_GPIO_Pin                        GPIO_PIN_13
#define MX_PE13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE12 */
#define MX_PE12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE12_Pin                             PE12
#define MX_PE12_GPIOx                           GPIOE
#define MX_PE12_PinState                        GPIO_PIN_RESET
#define MX_PE12_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE12_GPIO_Pin                        GPIO_PIN_12
#define MX_PE12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE15 */
#define MX_PE15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE15_Pin                             PE15
#define MX_PE15_GPIOx                           GPIOE
#define MX_PE15_PinState                        GPIO_PIN_RESET
#define MX_PE15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE15_GPIO_Pin                        GPIO_PIN_15
#define MX_PE15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE14 */
#define MX_PE14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE14_Pin                             PE14
#define MX_PE14_GPIOx                           GPIOE
#define MX_PE14_PinState                        GPIO_PIN_RESET
#define MX_PE14_GPIO_PuPd                       GPIO_NOPULL
#define MX_PE14_GPIO_Pin                        GPIO_PIN_14
#define MX_PE14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD15 */
#define MX_PD15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PD15_Pin                             PD15
#define MX_PD15_GPIOx                           GPIOD
#define MX_PD15_PinState                        GPIO_PIN_RESET
#define MX_PD15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PD15_GPIO_Pin                        GPIO_PIN_15
#define MX_PD15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE4 */
#define MX_PE4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE4_Pin                              PE4
#define MX_PE4_GPIOx                            GPIOE
#define MX_PE4_PinState                         GPIO_PIN_RESET
#define MX_PE4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PE4_GPIO_Pin                         GPIO_PIN_4
#define MX_PE4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

